### PR TITLE
Add legal-ish text to clarify licensing.

### PR DESCRIPTION
**Pull request by lukebakken**
This is in response to this [comment](https://github.com/tomas-abrahamsson/gpb/issues/60#issuecomment-247467432) on issue #60. Apparently, if you don't specifically say that code is un-licensed and un-copyrighted there could be issues around it at some point.

I added Apache to the list of licenses at the beginning of `COPYING.LIB` because, as of version 18, Erlang itself uses the Apache License 2.0, and not the EPL anymore ([source](http://www.erlang.org/about)).

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
You're right in EPL not being used any more for OTP, and the paragraphs need to be updated. However, thinking about it, I want to change the linking permissions to be even more relaxed: to allow linking with any code, not just APL 2.0. Regarding licensing for the generated code, I think gpb should not force it to be void of any license, but rather that it falls under the same licensing that applies to the `.proto` source files, [similiar to what the Google protobuf licensing says](https://github.com/google/protobuf/blob/master/LICENSE#L39L40)

So I'll update it, not exactly as this PR proposes, but in what I think is the spirit of the PR. Will push to a branch for review in a short while, in case there are any comments about it, keeping this PR open until the result has made it to `master.`

**Comment by lukebakken** [comment]
Thank you very much @tomas-abrahamsson !!

**Comment by tomas-abrahamsson** [comment]
In the just recently pushed branch `clarify-licensing`, there's some new wording, in case you would want to have a look at it before it goes into master.

**Comment by lukebakken** [comment]
Thank you @tomas-abrahamsson. I'll close this PR.

**Comment by tomas-abrahamsson** [comment]
Fine, I'll push the master containing the `clarify-licensing` change shortly (and delete the clarify branch on github). Should anything surface, it is always possible to make another change, no problems.

**Pull request closed without merging**
