### PR TITLE
Improve enum type specs

### PR DESCRIPTION
**Pull request by lrascao**
For every enum a typespec is defined with all the possible enum values as atoms, make use of the typespec when referencing enums.
This is useful because these typespecs could be used in methods defined in other modules

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
I think generally it is a good idea to make a type out of the enums. I'm pondering a little: on one hand, including `-type()`s in include files leads to possible name space collisions, next step along this path would be to introduce some option to configure the type's prefix or suffix, or possibly piggy-backing on the options for module or message prefix/suffix, widening their scope.

Another road to go is to instead include the type into the generated _.erl_ file, and `-export_type()` it. This naturally solves the name space problems, with no need for for prefixing or suffixing. Also, with the `-maps` option, no _.hrl_ file is generated, having it in the _.erl_ file instead works for both records and maps.

So I think it is a good idea, but I think it would get even better if it was defined in the _.erl_ file instead.

I don't remember from the top of my head which version of Erlang that first supported `-export_type()`, and there is no clearly defined oldest supported version of Erlang for gpb. So far, I've tried to support as old versions as reasonably possible, and for fancy "new" stuff, like maps, there's options to either enable (or possibly disable) it, if it is reasonably easy to do.

**Comment by lrascao** [comment]
I too agree that it would be a better option to have the types in .erl, i'll look into the export_type functionality and update the branch accordingly

**Comment by lrascao** [comment]
Updated the PR, the enum types are now defined in the .erl and exported from there also, i'm having a hard time finding out in what erlang version was export_type introduced, is there some sort of searchable changelog for erlang?

**Comment by tomas-abrahamsson** [comment]
I tried a simple module (below) with some old erlang installations that were mostly collecting dust on the disk. R12B-5 compiled the module without complaining, but R11B-5 complained, so it seems this is no issue anymore. Good.

The code looked fine, so I just merging it, forming 3.17.9. Thanks!

**Pull request merged**
