### PR TITLE
Small documentation changes for optional field options

### PR DESCRIPTION
**Pull request by lukebakken**

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
Thanks! I will fetch. I plan to amend the previous commit with your corrections, rather than add it as another correction. It means your name as committer will be lost, but I think the commit history looks better that way. Would that be ok with you? I'll mention in the commit message that you have contributed.  (If not ok, I'll add your commit on top, no problems, no big deal either)

**Comment by lukebakken** [comment]
That's no problem at all.

I'm running a bunch of Riak tests today using `gpb` and as of now it looks like all of the pieces are in place for `erlang_protobuffs` compatibility via the `ebp_compatibility` option. Thanks and I'll keep testing!

**Comment by tomas-abrahamsson** [comment]
Ok, cool!

**Comment by lukebakken** [comment]
@tomas-abrahamsson did you not want to use these changes?

**Comment by tomas-abrahamsson** [comment]
Oh, yes, indeed, I do! Sorry for confusion. The following have happened: I merged and amended locally as per earlier discussion, thus my local branch, and the branch on github had diverged. At this point, I decided (perhaps erroneously, see below) that I'd scrap the branch on github, and I guess since this was now a PR for a non-existing branch, that github decided it meant that the PR was closed. Hm. It looks like I've hit some `close` button, but that's not the case. I just deleted the branch on github.

I realize now you might be using the branch, perhaps still, for testing `epb_compatibility`, and so I should probably have pushed the updated (and diverged) branch instead of deleting it... Will do that. Sorry. Thanks for notifying.

**Comment by tomas-abrahamsson** [comment]
Pushed, and now I could reopen the issue again!

The following has happened: I pushed this branch again to github, but once I've pushed a new release on master, I intend to close this PR (and delete the branch again)

I've pushed another branch, `new-optionally-decode-omitted-optionals-to-defaults` (sorry for names getting longer and longer), that branch is what I'm merging to master (locally so far), later to be push as a new release (plus more commits).

The `new-optionally-...` branch contains this PR plus an extra eunit test, compared to this `optionally-...` branch. I think that should be the only difference.

**Comment by tomas-abrahamsson** [comment]
This is now included in 3.26.0 (closing)

**Pull request closed without merging**
