### PR TITLE
mark generated modules as private for docs

### PR DESCRIPTION
**Pull request by tsloughter**
I wasn't sure if this should be the default or if it should be `@hidden` or `@private`. So opening this to also ask what you'd want.

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
I think `@private` is the proper markup, and generally think this is a sensible addition. I'm in the process of adding generation of a few introspection functions that might be useful for gprc. I expect it will be ready with a day or two at most, is it ok to queue merging of this PR until that?

**Comment by tomas-abrahamsson** [comment]
Included in 4.5.0 which I just pushed

**Comment by tsloughter** [comment]
@tomas-abrahamsson awesome, thanks! Curious to find out what the new introspection functions provide, I might have use for them in the server or client side of https://github.com/tsloughter/grpcbox

**Comment by tomas-abrahamsson** [comment]
The idea I had with them was to provide some sort of way to convert between names as exposed over HTTP2 and "internal" names ie atoms. I guess it could maybe be come handy to automate the `service` mapping in the grpcbox, the `services => #{'grpc.testing.TestService' => grpc_testing_test_service}` in the `grpc_opts`, or so. Here's an exceprt of what is generated, if the test.proto of grpcbox would have been compiled with the `{rename,{rpc_name,snakecase}}` option:
```
fqbins_to_service_and_rpc_name(<<"grpc.testing.TestService">>, <<"EmptyCall">>) ->
    {'grpc.testing.TestService', empty_call};
fqbins_to_service_and_rpc_name(<<"grpc.testing.TestService">>, <<"UnaryCall">>) ->
    {'grpc.testing.TestService', unary_call};
...
```
An inverse function is also generate, so they can be useful both on the server and client side.

Also generated is the following with a corresponding inverse:
```
fqbin_to_service_name(<<"grpc.testing.TestService">>) ->
    'grpc.testing.TestService';
...

service_name_to_fqbin('grpc.testing.TestService') ->
    <<"grpc.testing.TestService">>;
...
```

If it would have been possible to compile `test.proto` without the `use_packages` option, this is what the generated functions would have looked like instead (similarly for `fqbins_to_service_and_rpc_name`):
```
fqbin_to_service_name(<<"grpc.testing.TestService">>) -> 'TestService';
...
service_name_to_fqbin('TestService') -> <<"grpc.testing.TestService">>;
...
```

Hope this can provide some insights, and of course also that it could be useful for something. I admit I've been mostly guessing on what may be useful, so any suggestions are appreciated.

**Pull request merged**
