### PR TITLE
Correct type specs for encode_msg args

### PR DESCRIPTION
**Pull request by moxley**
Referencing issue brought up in lrascao/rebar3_gpb_plugin#51. Fixes dialyzer failure when passing `-Wunderspecs` option. This change adds proper type specs to the `encode_msg` generated function.

I apologize for the bad code. I'm not an Erlang dev.

### CODE REVIEW

**Comment by moxley** [comment]
Looks like the build is failing with this change, so I might have to give up and try another route for our stuff.

**Comment by tomas-abrahamsson** [comment]
I was actually pondering a suitable way forward for that issue right now :) I also suppose this pr might also indicate you're in a bit of a hurry regarding the #117? If so, maybe it'd be better to make a release of #117 and we could take this a later on, what do you think?

 I haven't looked too closely yet at details of this PR, but I think it fails when generating for maps, because then there are no records to reference. I was considering making an exported union type for all messages or maps, preferably `msg()` and use that one in the `-spec`. But the sort-of-stopper was namespacing: with the type spec option, all enums and messages are exported, named as is. While google's protobuf mandates messages to begin with an upper case letter (I think), gpb does not, and so there may be many proto files with lower case message names, and there may be collisions with a `msg()` type. This was what I was pondering.

**Comment by moxley** [comment]
Yeah, we are hoping for a new release that includes #117. Without a release, we do have another way forward we are looking into. At the same time, another member of our team with real Erlang experience will look at this PR and see what he can do.

**Comment by tomas-abrahamsson** [comment]
I added a few fixup commits to make the generated code a bit better and pass the tests.

Since there are a few commits that have been fixed up, could you squash them? Preferably squash the entire branch to one commit, I think this makes most sense in this case, and will make any future git bisect work easier when all commits passes tests.

**Comment by kbaird** [comment]
Hi, @tomas-abrahamsson. Thanks for taking our in-progress work and finalizing it. I've squashed the commits in https://github.com/GhostGroup/gpb/tree/encode-specs as you requested. Please let me know if anything is not to your liking.

**Comment by tomas-abrahamsson** [comment]
Thanks! Included in 3.28.0 which I just pushed, hence closing this ticket. If there's anything, just feel free to re-open or open another ticket.

**Pull request merged**
